services:
  - docker

language: bash

before_install:
- git config --global user.email "you@example.com"
- git config --global user.name "Your Name"

script:
- make test
- docker build -t git-secrets-ubuntu:latest docker/ubuntu/
