services:
  - docker

language: bash

before_install:
- git config --global user.email "awslabs@amazon.com"
- git config --global user.name "Awslabs"

matrix:
  include:
  - env: BASH_VER=4.0
  - env: GIT_VER=1:2.7.4-0ubuntu1 BASH_VER=4.0
  - env: GIT_VER=1:1.9.1-1ubuntu0.6 BASH_VER=4.0
  allow_failures:
  - env: GIT_VER=1:2.7.4-0ubuntu1 BASH_VER=3.0
  - env: GIT_VER=1:1.9.1-1ubuntu0.6 BASH_VER=3.0

script:
- make test
- docker run -it  -v $PWD/docker-run.sh:/run.sh -e "GIT_VER=$GIT_VER" -e "BASH_VER=$BASH_VER" ubuntu /run.sh
